In [1]:
from abc import ABC, abstractmethod
from typing import Optional, Union, Iterable
from collections.abc import Iterator
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np

In [189]:
df.describe()

index       post_id      estrato         Area     bedrooms  \
count  9497.000000  9.497000e+03  9497.000000  9497.000000  9497.000000   
mean   1212.262715  6.104147e+06     4.107297   155.906391     3.133095   
std     987.692246  1.152608e+06     0.824518   130.409756     1.505738   
min       1.000000  9.098480e+05     1.000000     1.000000     0.000000   
25%     346.000000  5.439663e+06     4.000000    80.000000     3.000000   
50%     905.000000  6.569660e+06     4.000000   110.000000     3.000000   
75%    2044.000000  7.018111e+06     5.000000   175.000000     3.000000   
max    3400.000000  7.196630e+06     5.000000   990.000000    20.000000   

         bathrooms      garages         Price  
count  9497.000000  9497.000000  9.497000e+03  
mean      2.543329     1.118353  7.045135e+08  
std       1.222353     0.899954  1.279075e+10  
min       0.000000     0.000000  1.500000e+07  
25%       2.000000     1.000000  2.400000e+08  
50%       2.000000     1.000000  3.400000e+08  
75%       3.000000     1.000000  5.200000e+08  
max      10.000000    10.000000  9.000000e+11

In [34]:
type(df_subset.iloc[:, :-1])

pandas.core.frame.DataFrame

In [35]:
type(df_subset.iloc[:, -1])

pandas.core.series.Series

In [144]:
class df_data_source():
    def __init__(self,data_source):
        self.data_source = data_source
    def split_data(self,test_size_):
        self.test_size_ = test_size_
        self.price_subset = self.data_source.iloc[:, -1].values
        self.non_price_subset = self.data_source.iloc[:, :-1].values
        self.price_subset_train, self.price_subset_test,self.data_subset_train, self.data_subset_test = train_test_split(self.price_subset, self.non_price_subset, test_size=self.test_size_, shuffle=True, random_state=0, train_size=0.3)
    def reshape_data(self):
        self.price_subset_train = self.price_subset_train.reshape(-1, 1)
        self.price_subset_test = self.price_subset_train.reshape(-1, 1)

class Predictor():
    def __init__(self,source_model):
        self.source_model = source_model
    def get_prediction(self,prediction_data):
        estimated_price = self.source_model.predict(prediction_data)

class Prediction_data():
    def __init__(self,estrato,area,bedrooms,bathrooms,garages):
        self.estrato = estrato
        self.area = area
        self.bedrooms = bedrooms
        self.bathrooms = bathrooms
        self.garages = garages
        self.list = []
        self.prediction_array = np.array(self.list)
    def get_prediction_array(self):
        self.list = [self.estrato, self.area, self.bedrooms, self.bathrooms, self.garages]
        self.prediction_array = np.array(self.list)  
        self.prediction_array = self.prediction_array.reshape(1,-1)

In [199]:
class data(ABC):
    @abstractmethod
    def load_data(self,data_list,data_source):
        for i,row  in data_source.iterrows():
            data = House_data(
            condition = row["condition"],
            property_type = row["property_type"],
            neighborhood = row["neighborhood"],
            estrato = row["estrato"],
            area = row["area"],
            bedrooms = row["bedrooms"],
            bathrooms = row["bathrooms"],
            garages = row["garages"],
            price = row["price"])
        data_list.append(data)
        
class Training_data(data):
    def __init__(self,training_data):
        self.training_data : list[House_data] = []

class Testing_data(data):
    def __init__(self,testing_data):
        self.testing_data : list[House_data] = []
        
class House_data():
    def __init__(
        self,
        condition : str,
        property_type : str,
        neighborhood : str,
        estrato : int,
        area : int,
        bedrooms : int,
        bathrooms : int,
        garages : int,
        price: Optional[int]
       ):
        self.condition = condition
        self.property_type = property_type
        self.neighborhood = neighborhood
        self.estrato = estrato
        self.area = area
        self.bedrooms = bedrooms
        self.bathrooms = bathrooms
        self.garages = garages
        self.price: Optional[int]

In [5]:
df = pd.read_csv("C:\\Users\\ends0\\Downloads\\df_posts_housing.csv")

In [6]:
df.head()

index  post_id                                         post_title  \
0      1  7172619  Usado$250.000.000 COP224m² • 3ha. • 1ba.villac...   
1      2  7127871  UsadoInmobiliaria$240.000.000 COP88m² • 3ha. •...   
2      3  7187797  Usado$70.000.000 COP104m² • 3ha. • 1ba.bosque ...   
3      4  7037686  UsadoInmobiliaria$1.200.000.000 COP600m² • 3ba...   
4      5  7162861  UsadoInmobiliaria$350.000.000 COP4m² • 3ha. • ...   

  bussiness_type condition  estrato property_type          city  neighborhood  \
0          Venta     Usado        1          Casa  barranquilla  villacevilla   
1          Venta     Usado        1   Apartamento  barranquilla      el-prado   
2          Venta     Usado        1          Casa  barranquilla        bosque   
3          Venta     Usado        1          Casa  barranquilla    alto-prado   
4          Venta     Usado        1          Casa  barranquilla       paraiso   

   Area  bedrooms  bathrooms  garages  \
0   224         3          1        0   
1    88         3          2        1   
2   104         3          1        0   
3   600         3          5        0   
4     4         3          3        1   

                                           post_link       Price  
0  https://www.fincaraiz.com.co/inmueble/casa-en-...   250000000  
1  https://www.fincaraiz.com.co/inmueble/apartame...   240000000  
2  https://www.fincaraiz.com.co/inmueble/casa-en-...    70000000  
3  https://www.fincaraiz.com.co/inmueble/casa-en-...  1200000000  
4  https://www.fincaraiz.com.co/inmueble/casa-en-...   350000000

In [7]:
df.tail()

index  post_id                                         post_title  \
9492   3396  7091439  UsadoInmobiliaria$260.000.000 COP60m² • 2ha. •...   
9493   3397  6903421  UsadoInmobiliaria$480.000.000 COP110,12m² • 4h...   
9494   3398  7170150  UsadoInmobiliaria$320.000.000 COP112m² • 3ha. ...   
9495   3399  5818751  UsadoInmobiliaria$720.000.000 COP512m² • 4ha. ...   
9496   3400  7064589  UsadoInmobiliaria$400.000.000 COP98m² • 3ha. •...   

     bussiness_type condition  estrato property_type          city  \
9492          Venta     Usado        5   Apartamento  barranquilla   
9493          Venta     Usado        5   Apartamento  barranquilla   
9494          Venta     Usado        5   Apartamento  barranquilla   
9495          Venta     Usado        5          Casa  barranquilla   
9496          Venta     Usado        5   Apartamento  barranquilla   

       neighborhood  Area  bedrooms  bathrooms  garages  \
9492  ciudad-jardin    60         2          1        1   
9493   villa-santos   110         4          5        0   
9494  ciudad-jardin   112         3          2        1   
9495  ciudad-jardin   512         4          4        2   
9496  ciudad-jardin    98         3          3        1   

                                              post_link      Price  
9492  https://www.fincaraiz.com.co/inmueble/apartame...  260000000  
9493  https://www.fincaraiz.com.co/inmueble/apartame...  480000000  
9494  https://www.fincaraiz.com.co/inmueble/apartame...  320000000  
9495  https://www.fincaraiz.com.co/inmueble/casa-en-...  720000000  
9496  https://www.fincaraiz.com.co/inmueble/apartame...  400000000

In [8]:
df_subset = df[df["neighborhood"] == "el-prado"]

In [9]:
df_subset = df

In [10]:
df_subset.head()

index  post_id                                         post_title  \
0      1  7172619  Usado$250.000.000 COP224m² • 3ha. • 1ba.villac...   
1      2  7127871  UsadoInmobiliaria$240.000.000 COP88m² • 3ha. •...   
2      3  7187797  Usado$70.000.000 COP104m² • 3ha. • 1ba.bosque ...   
3      4  7037686  UsadoInmobiliaria$1.200.000.000 COP600m² • 3ba...   
4      5  7162861  UsadoInmobiliaria$350.000.000 COP4m² • 3ha. • ...   

  bussiness_type condition  estrato property_type          city  neighborhood  \
0          Venta     Usado        1          Casa  barranquilla  villacevilla   
1          Venta     Usado        1   Apartamento  barranquilla      el-prado   
2          Venta     Usado        1          Casa  barranquilla        bosque   
3          Venta     Usado        1          Casa  barranquilla    alto-prado   
4          Venta     Usado        1          Casa  barranquilla       paraiso   

   Area  bedrooms  bathrooms  garages  \
0   224         3          1        0   
1    88         3          2        1   
2   104         3          1        0   
3   600         3          5        0   
4     4         3          3        1   

                                           post_link       Price  
0  https://www.fincaraiz.com.co/inmueble/casa-en-...   250000000  
1  https://www.fincaraiz.com.co/inmueble/apartame...   240000000  
2  https://www.fincaraiz.com.co/inmueble/casa-en-...    70000000  
3  https://www.fincaraiz.com.co/inmueble/casa-en-...  1200000000  
4  https://www.fincaraiz.com.co/inmueble/casa-en-...   350000000

In [11]:
df_subset.tail()

index  post_id                                         post_title  \
9492   3396  7091439  UsadoInmobiliaria$260.000.000 COP60m² • 2ha. •...   
9493   3397  6903421  UsadoInmobiliaria$480.000.000 COP110,12m² • 4h...   
9494   3398  7170150  UsadoInmobiliaria$320.000.000 COP112m² • 3ha. ...   
9495   3399  5818751  UsadoInmobiliaria$720.000.000 COP512m² • 4ha. ...   
9496   3400  7064589  UsadoInmobiliaria$400.000.000 COP98m² • 3ha. •...   

     bussiness_type condition  estrato property_type          city  \
9492          Venta     Usado        5   Apartamento  barranquilla   
9493          Venta     Usado        5   Apartamento  barranquilla   
9494          Venta     Usado        5   Apartamento  barranquilla   
9495          Venta     Usado        5          Casa  barranquilla   
9496          Venta     Usado        5   Apartamento  barranquilla   

       neighborhood  Area  bedrooms  bathrooms  garages  \
9492  ciudad-jardin    60         2          1        1   
9493   villa-santos   110         4          5        0   
9494  ciudad-jardin   112         3          2        1   
9495  ciudad-jardin   512         4          4        2   
9496  ciudad-jardin    98         3          3        1   

                                              post_link      Price  
9492  https://www.fincaraiz.com.co/inmueble/apartame...  260000000  
9493  https://www.fincaraiz.com.co/inmueble/apartame...  480000000  
9494  https://www.fincaraiz.com.co/inmueble/apartame...  320000000  
9495  https://www.fincaraiz.com.co/inmueble/casa-en-...  720000000  
9496  https://www.fincaraiz.com.co/inmueble/apartame...  400000000

In [12]:
df_subset = df_subset.drop(['index','post_id','post_title','city','post_link'], axis = 1)

In [13]:
df_subset = df_subset.drop(['bussiness_type','condition','property_type','neighborhood'], axis = 1)

In [14]:
df_subset.head()

estrato  Area  bedrooms  bathrooms  garages       Price
0        1   224         3          1        0   250000000
1        1    88         3          2        1   240000000
2        1   104         3          1        0    70000000
3        1   600         3          5        0  1200000000
4        1     4         3          3        1   350000000

In [118]:
data_subset = df_data_source(df_subset)

In [119]:
data_subset.split_data(0.05)

In [120]:
type(data_subset.data_subset_test)

numpy.ndarray

In [121]:
from sklearn.linear_model import LinearRegression

In [122]:
linear_reg = Predictor(LinearRegression())

In [130]:
data_subset.data_subset_train

array([[  4, 216,   3,   1,   0],
       [  4,  37,   2,   1,   0],
       [  5,  98,   3,   2,   1],
       ...,
       [  4,  63,   3,   2,   1],
       [  5, 117,   3,   2,   3],
       [  5,  85,   3,   2,   1]], dtype=int64)

In [131]:
data_subset.price_subset_train

array([[350000000],
       [120000000],
       [380000000],
       ...,
       [270000000],
       [260000000],
       [310000000]], dtype=int64)

In [125]:
data_subset.reshape_data()

In [126]:
len(data_subset.data_subset_train)

2849

In [127]:
len(data_subset.price_subset_train)

2849

In [128]:
linear_reg.source_model.fit(data_subset.data_subset_train,data_subset.price_subset_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [133]:
linear_reg.source_model.score(data_subset.data_subset_train,data_subset.price_subset_train)

0.01712096606605029

In [137]:
data_subset.data_subset_train

array([[  4, 216,   3,   1,   0],
       [  4,  37,   2,   1,   0],
       [  5,  98,   3,   2,   1],
       ...,
       [  4,  63,   3,   2,   1],
       [  5, 117,   3,   2,   3],
       [  5,  85,   3,   2,   1]], dtype=int64)

In [145]:
p1 = Prediction_data(4,120,4,1,2)

In [146]:
p1.get_prediction_array()

In [143]:
p1.prediction_array.reshape(1,-1)

array([[  4, 120,   4,   1,   2]])

In [147]:
linear_reg.source_model.predict(p1.prediction_array)

array([[-2.78260491e+09]])

In [148]:
linear_reg.source_model.coef_

array([[-5.19792594e+07,  5.60774666e+06, -7.65611927e+07,
         1.82352959e+09, -6.62558747e+08]])

In [149]:
linear_reg.source_model.intercept_

array([-3.4397848e+09])

In [150]:
print(data_subset.price_subset_train)

[[350000000]
 [120000000]
 [380000000]
 ...
 [270000000]
 [260000000]
 [310000000]]


In [151]:
print(data_subset.data_subset_train)

[[  4 216   3   1   0]
 [  4  37   2   1   0]
 [  5  98   3   2   1]
 ...
 [  4  63   3   2   1]
 [  5 117   3   2   3]
 [  5  85   3   2   1]]
